### ISSUE TITLE
Removing hotspots

### ISSUE THREAD

**Issue by heibjornendre** [Arthyon/Creuna.FluidImages#1]
Great functionality, this is a need-to-have on modern web solutions!

However it would be nice to have the possibility to remove hotspots too so the default values kicks in.

**Comment by Arthyon** [comment]
Added in [release 0.0.2-beta](https://github.com/Arthyon/Creuna.FluidImages/releases/tag/v0.0.2-beta).
6fad270fb68b1848fc2c0d4b9815d561961470b0
